Fix procedural pipeline on dev
NPCMS/ElementalExplorers pull request #156
Opened 2023-03-04 18:11 UTC by uq20042

2023-03-05 12:13 UTC, James-Millan commented
will be branching off here for the meantime, need alexs approval or to fix the networking stuff then we'll merge to dev

2023-03-06 12:29 UTC, alexelwood14 commented
Merge the PR for fix-dev-netcode into this branch before merging this PR. I will approve this PR once that has happened.

2023-03-06 12:36 UTC, alexelwood14 requested changes
See previous comment

2023-03-06 12:54 UTC, James-Millan approved these changes

2023-03-06 12:55 UTC, alexelwood14 approved these changes

2023-03-06 12:55 UTC, merged